"""
tests/test_authz_matrix.py — Systematic authorization coverage: every route in api.py, checked
against all three real session states (no session, bettor session, owner session) over real HTTP
via TestClient. No mocking of the auth layer itself — real signed session cookies, real DB.

Closes a gap flagged explicitly in docs/test-strategy.md: "No test asserting a bettor session
gets 403 on every /api/admin/* route." Ad hoc coverage of specific admin actions already exists
in test_e2e.py; this is the first EXHAUSTIVE, systematic pass over every route at once, so a
route added later without the expected auth call — or one accidentally removed — fails loudly
here instead of silently shipping.

The route inventory below was generated by scanning api.py for which of _require()/_require_owner()
each handler actually calls (not inferred from path naming or copied by hand) — see the repo audit
this file came out of. If a route's auth level changes, this file's inventory must be updated to
match, and that update is itself the record of an intentional decision.
"""
import os, sys, tempfile

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(_HERE))

_TMPDIR = tempfile.mkdtemp(prefix="swimbet_authz_")
os.environ["DATABASE_URL"] = f"sqlite:///{os.path.join(_TMPDIR, 'authz.db')}"
os.environ["AUTH_MODE"] = "name"
os.environ["ADMIN_PASSWORD"] = "e2e-test-admin-pw"
os.environ["SESSION_SECRET"] = "e2e-test-session-secret-" + "x" * 20
os.environ["ALLOW_HTTP"] = "1"
os.environ.pop("SWIMBET_DEV", None)
os.environ.pop("GOOGLE_CLIENT_ID", None)

import pytest
from fastapi.testclient import TestClient

import api
import store


@pytest.fixture(autouse=True)
def fresh_db():
    store.meta.drop_all(store.engine)
    store.init()
    api._login_attempts.clear()  # module-global rate-limit state — isolate tests from each other
    api._name_claims.clear()     # module-global name-collision memory — same reason
    yield


def admin_client():
    c = TestClient(api.app)
    r = c.post("/auth/admin", json={"password": "e2e-test-admin-pw"})
    assert r.status_code == 200
    return c


def user_client(name="Matrix Bettor"):
    c = TestClient(api.app)
    r = c.post("/auth/name", json={"name": name})
    assert r.status_code == 200
    return c


def anon_client():
    return TestClient(api.app)


# ── route inventory ──────────────────────────────────────────────────────────────────────────────
# (method, path, valid_body) — a real, schema-valid body for every route that requires one. Auth
# checks run INSIDE the handler body (not as a FastAPI Depends), so Pydantic body/path validation
# happens first regardless of session state — an invalid body would 422 before ever reaching the
# auth check, silently masking exactly what this file exists to test. Every body here is chosen to
# pass validation; what happens AFTER auth (a 200, or a domain-rule 400) is out of scope — that's
# already covered by test_e2e.py's per-endpoint tests.

AUTHED_ROUTES = [
    ("GET",  "/api/state",       None),
    ("POST", "/api/bets",        {"outcome": "khuseel", "amount": 100}),
    ("POST", "/api/bets/cancel", {}),
    ("GET",  "/api/settlement",  None),
]

OWNER_ROUTES = [
    ("GET",  "/api/admin/pending",              None),
    ("GET",  "/api/admin/projected-payouts",    None),
    ("GET",  "/api/admin/bets",                 None),
    ("POST", "/api/admin/bets/999999/approve",  None),
    ("POST", "/api/admin/bets/999999/reject",   None),
    ("POST", "/api/admin/bets/999999/status",   {"status": "pending"}),
    ("POST", "/api/admin/bets/manual",
     {"name": "Matrix Walk-in", "outcome": "khuseel", "amount": 100}),
    ("POST", "/api/admin/house-seed",           {"outcome": "khuseel", "amount": 0}),
    ("POST", "/api/admin/side-seeds",           {"per_market": 0}),
    ("POST", "/api/admin/bets/void",            {"key": "name:nobody"}),
    ("POST", "/api/admin/markets/match/resume", None),
    ("POST", "/api/admin/markets/match/suspend", None),
    ("POST", "/api/admin/markets/recheck",      None),
    ("POST", "/api/admin/race/start-lap",       None),
    ("POST", "/api/admin/race/lap-result",      {"winner": "khuseel"}),
    ("POST", "/api/admin/settle",               None),
    ("POST", "/api/admin/seed",                 None),
    ("POST", "/api/admin/reset-book",           None),
]

STREAM_ROUTE = ("GET", "/api/stream", None)  # excluded from the generic lists — see below


def _ids(routes):
    return [f"{m}:{p}" for m, p, _ in routes]


def _call(client, method, path, body):
    if method == "GET":
        return client.get(path)
    return client.post(path, json=body if body is not None else {})


# ── negative: no session at all → 401 on every protected route (incl. the stream route: an
# unauthenticated request is rejected before the response ever becomes a live stream, so a plain
# .get() here is safe and won't hang) ───────────────────────────────────────────────────────────

@pytest.mark.parametrize("method,path,body", AUTHED_ROUTES + OWNER_ROUTES + [STREAM_ROUTE],
                         ids=_ids(AUTHED_ROUTES + OWNER_ROUTES + [STREAM_ROUTE]))
def test_no_session_gets_401(method, path, body):
    r = _call(anon_client(), method, path, body)
    assert r.status_code == 401, f"{method} {path} should 401 with no session, got {r.status_code}: {r.text}"
    assert r.json()["detail"] == "not_authenticated"


# ── negative: authenticated bettor (not owner) → 403 on every owner-only route, and specifically
# 403 not 401 — proves the identity check and the role check are two distinct, correctly layered
# gates (_require_owner calls _require first; a truly unauthenticated request to the same route
# gets 401, tested above) ────────────────────────────────────────────────────────────────────────

@pytest.mark.parametrize("method,path,body", OWNER_ROUTES, ids=_ids(OWNER_ROUTES))
def test_bettor_session_gets_403_on_owner_routes(method, path, body):
    r = _call(user_client(), method, path, body)
    assert r.status_code == 403, f"{method} {path} should 403 for a bettor, got {r.status_code}: {r.text}"
    assert r.json()["detail"] == "owner_only"


# ── positive control: legitimate sessions are NOT blocked by auth. Without this, the negative
# tests above could be passing for the wrong reason (e.g. a route that 401s/403s for EVERYONE due
# to an unrelated bug would still "pass" a bettor-gets-403 check) ──────────────────────────────

@pytest.mark.parametrize("method,path,body", AUTHED_ROUTES, ids=_ids(AUTHED_ROUTES))
def test_bettor_session_not_blocked_on_authed_routes(method, path, body):
    r = _call(user_client(), method, path, body)
    assert r.status_code not in (401, 403), \
        f"{method} {path} wrongly blocked a bettor session: {r.status_code}: {r.text}"


@pytest.mark.parametrize("method,path,body", AUTHED_ROUTES + OWNER_ROUTES,
                         ids=_ids(AUTHED_ROUTES + OWNER_ROUTES))
def test_owner_session_not_blocked_anywhere(method, path, body):
    r = _call(admin_client(), method, path, body)
    assert r.status_code not in (401, 403), \
        f"{method} {path} wrongly blocked the owner: {r.status_code}: {r.text}"


# ── /api/stream: excluded from the generic positive-control lists above because it's a genuinely
# infinite connection (20s keepalive pings, never completes on its own). TestClient drives the
# ASGI app to full completion synchronously in the calling thread before returning ANYTHING — so
# both .get() and .stream()'s context-manager form hang forever on a SUCCESSFUL (non-rejected)
# request here, unlike every other route in this file (confirmed directly: an earlier version of
# this test using `with client.stream(...)` hung the whole suite). The rejection case (no
# session) is safe as a plain .get() above — it 401s before the stream generator ever starts.

def test_stream_accessible_to_any_authenticated_session_bettor_and_owner():
    """For the positive case, run the request in a background daemon thread and confirm it's
    STILL blocked after a few seconds: the 401 test above proves a REJECTED request returns in
    well under a second, so "still open after 3s" is itself the proof this connection was
    accepted and is genuinely streaming, not rejected — without needing to gracefully terminate
    an intentionally-infinite response."""
    import threading

    def hold_open(client, done):
        client.get("/api/stream")  # blocks until the stream ends, which it never does on success
        done.set()

    for make_client in (user_client, admin_client):
        done = threading.Event()
        t = threading.Thread(target=hold_open, args=(make_client(), done), daemon=True)
        t.start()
        finished_early = done.wait(timeout=3)
        assert not finished_early, "stream ended/was rejected within 3s -- expected it to stay open"


# ── edge case: a tampered/garbage session cookie must fail closed (401), not crash or silently
# authenticate as someone ──────────────────────────────────────────────────────────────────────

def test_tampered_session_cookie_is_treated_as_unauthenticated():
    c = TestClient(api.app)
    c.cookies.set("session", "not-a-real-itsdangerous-signed-cookie")
    r = c.get("/api/state")
    assert r.status_code == 401


# ── public routes: must NOT require a session, and the routes that gate on an env var (not a
# session) must show the correct posture for this test environment ────────────────────────────

def test_config_and_healthz_are_public():
    c = anon_client()
    assert c.get("/api/config").status_code == 200
    assert c.get("/healthz").status_code == 200


def test_auth_routes_are_reachable_without_a_prior_session():
    """These are exactly how a session GETS created — they must not themselves require one."""
    r = anon_client().post("/auth/name", json={"name": "Fresh Bettor"})
    assert r.status_code == 200

    r2 = anon_client().post("/auth/admin", json={"password": "wrong-password"})
    assert r2.status_code == 403 and r2.json()["detail"] == "wrong_password"  # not 401


def test_test_login_route_disabled_when_env_var_unset():
    """TEST_LOGIN_PASSWORD is deliberately unset in this test env, mirroring production (where it
    must also be unset — risk register R-9). Confirms the auth-bypass route stays a 404, not a
    silently-reachable backdoor, when the feature is off."""
    r = anon_client().post("/auth/test", json={"email": "someone@seekhoapp.com", "password": "x"})
    assert r.status_code == 404


def test_spa_catchall_is_public():
    r = anon_client().get("/some/random/frontend/route")
    assert r.status_code == 200  # serves index.html regardless of session


# ── completeness check: fail loudly if a new route is added to api.py without being added here
# too, instead of silently under-covering it forever ────────────────────────────────────────────

def test_route_inventory_matches_api_py():
    """If this fails, a route was added to (or removed from) api.py without a matching update to
    the AUTHED_ROUTES/OWNER_ROUTES/public-route lists above — go classify it and add it."""
    covered = {p for _, p, _ in AUTHED_ROUTES + OWNER_ROUTES} | {
        "/api/stream", "/api/config", "/healthz", "/auth/name", "/auth/admin", "/auth/test",
        "/auth/login", "/auth/callback", "/auth/logout",
    }
    # path params in api.py's own routes use {..} placeholders; normalize ours the same way for
    # the ones that carry a real id/market so the comparison is apples to apples.
    covered_normalized = {
        p.replace("/999999/", "/{bet_id}/").replace("/match/", "/{market_id}/") for p in covered
    }
    actual = {
        route.path for route in api.app.router.routes
        if getattr(route, "path", None) and route.path not in ("/{full_path:path}",)
        and hasattr(route, "methods")
    }
    missing = actual - covered_normalized
    assert not missing, f"route(s) present in api.py but not classified in this test file: {missing}"
